### ISSUE TITLE
Api projesine ulaşılamaması

### ISSUE THREAD

**Issue by okandavut** [Alertis/sanal-sinav-sistemi#1]
Selamlar, elinize sağlık proje çok güzel olmuş :)

Api projesini incelemek istedigimde ulaşamadım. Bilginiz olsun :) https://github.com/toltarisa/YazilimSinamaBackendProjesi

**Comment by Alertis** [comment]
Çok teşekkür ederiz. API tarafını henüz public durumuna getiremedik. @toltarisa yakın zamanda api projesini de public yapacaktır :)
